### ISSUE TITLE
Question: Should useTab === false to trigger the statusbar warning?

### ISSUE THREAD

**Issue by shabegom** [vslinko/obsidian-outliner#143]
Looking at this line:

https://github.com/vslinko/obsidian-outliner/blob/ff313258c189f513ce3c9c06615e4f088ecfbe5d/src/features/ListsStylesFeature.ts#L49

Having a debate with some folks around the status bar warning. I understand that if we're using spaces as tabs the `tabSize` setting should equal 4. But, if `useTabs` is toggled on, it doesn't use space characters for indentation. So wouldn't you want to show the warning if `useTabs` was false?

**Comment by vslinko** [comment]
@shabegom `useTabs = false` also has a problem - indent lines don't work with spaces:

<img width="249" alt="Screenshot 2021-05-24 at 18 17 18" src="https://user-images.githubusercontent.com/205823/119369212-971bff00-bcbc-11eb-9bee-c9810763bb8e.png">
<img width="229" alt="Screenshot 2021-05-24 at 18 17 33" src="https://user-images.githubusercontent.com/205823/119369222-9a16ef80-bcbc-11eb-8288-6062c880ae53.png">
<img width="250" alt="Screenshot 2021-05-24 at 18 17 48" src="https://user-images.githubusercontent.com/205823/119369229-9be0b300-bcbc-11eb-96ac-755d04664759.png">

I created this alert because I was approached with the problem — https://github.com/vslinko/obsidian-outliner/issues/41#issuecomment-812934654

I don't want to remove the warning, but I can create a `Hide status bar warning' toggle.

**Comment by vslinko** [comment]
I'm sorry, I misunderstood the question. I think yes, it's worth adding a warning when `useTab = false`.

**Comment by vslinko** [comment]
Released in https://github.com/vslinko/obsidian-outliner/releases/tag/1.2.5
