### ISSUE TITLE
[BUG] Hotkeys not working

### ISSUE THREAD

**Issue by davideliotmanuel** [vslinko/obsidian-outliner#161]
**Describe the bug**
Hotkeys not working, Enhance Cmd+A not working

**Expected behavior**
Expected to be able to move blocks up and down, hit Cmd+A twice to select the current block.

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Obsidian Version: 0.12.4

**Additional context**
Have tried turning off all other plugins, have tried uninstalling and reinstalling obsidian. No luck. 

Had a friend who is a more experienced obsidian user look over my obsidian settings and nothing about them stuck out as odd to him.

**Comment by byniutek** [comment]
Hey Guys 
I can confirm hotkeys stopped working for me either. 
Not sure but it might be a regression after  recent `0.12.15` release  ?

**Comment by bitbatstudios** [comment]
FWIW -- I realized that some of the hotkeys that weren't working for me
were because I wasn't following the stricter markdown rules for creating
lists (as I was previously using Roam which makes lists with less strict
rules). Once I was following the markdown rules (i.e., start a list with a
dash followed by a space) the move up and move down hotkeys were working
within those lists.

The Cmd+A hotkey only works with the advanced functionality that this
plugin provides *if I'm within a list*. If I try to use it within a
paragraph that is not a list, it just selects the full page. I think that
this is how the plugin is supposed to work, though. If not, then that's
still a problem I'm having. But if so, then from my end this is resolved.

**Comment by vslinko** [comment]
Hi!

Could you please provide some examples of documents where the hotkeys doesn't work?

**Comment by davideliotmanuel** [comment]
Right now the double Cmd+A hotkey isn't working for me across all the pages
in my database unless I use it within a properly formatted list. But if I
try to use it while my cursor is in the middle of a paragraph, for
instance, it will not work (i.e., in this case when I hit Cmd-A it just
selects the full page, and if I hit it a second time nothing different
happens).

I've tried starting fresh databases and the problem still happens for me.

Maybe this is a functionality limit and I'm just not aware that having it
work from within paragraphs isn't supported?

**Comment by vslinko** [comment]
<kbd>Cmd</kbd><kbd>A</kbd> should only work in properly formatted lists, this is true. Do you have any other problems with the hotkeys?

**Comment by vslinko** [comment]
@byniutek Could you please describe more about your problem?

**Comment by davideliotmanuel** [comment]
Ahh, okay. Then all is working as intended. I'm not having any other
problems with the hotkeys.
