### ISSUE TITLE
[BUG] Soft line wrap doesn't work well on the first level

### ISSUE THREAD

**Issue by WhiteNoiseDev** [vslinko/obsidian-outliner#246]
Soft line break (Shift-Enter) introduced here <https://github.com/vslinko/obsidian-outliner/issues/38>
doesn't work well on the first level.

![Animation06](https://user-images.githubusercontent.com/3163647/148689161-7fa70a21-6066-4b69-856e-1f049c633245.gif)

**Comment by WhiteNoiseDev** [comment]
Perhaps the alignment of the other levels could be improved as well.

**Comment by vslinko** [comment]
@WhiteNoiseDev thank you for your feedback!

I don't think this problem can be fixed in the Outlier plugin. This alignment depends on the user's "Use Tab" and "Tab Size" settings, and on the user's font. The only thing I can do is force users to use spaces, but I think that's a bad idea.

If you have any other ideas how to fix this, please tell me.

**Comment by WhiteNoiseDev** [comment]
I think this is a byproduct of the changes made to the way the bullet point is rendered.

Aside from this, i still don't understand why you add a tab to the second line of level 1. In that case, there should only be 2 spaces.

**Comment by vslinko** [comment]
I can do that but it doesn't help:

![Screen Recording 2022-01-16 at 17 37 50 mov](https://user-images.githubusercontent.com/205823/149664602-99f5fe2c-a295-4ed9-b61a-de24af3747de.gif)

**Comment by vslinko** [comment]
You need to use monospace font to make 2 spaces work.

**Comment by WhiteNoiseDev** [comment]
yes, to make things align perfectly you need monospace.

**Comment by vslinko** [comment]
@WhiteNoiseDev implemented 2 spaces approach in https://github.com/vslinko/obsidian-outliner/releases/tag/2.2.0
