### ISSUE TITLE
[enhancement] Requirement for Legacy Editor to be disabled

### ISSUE THREAD

**Issue by jasondavis** [vslinko/obsidian-outliner#249]
Please consider possibly building in a setting/option to make v1 of outliner and zoom plugin work with Obsidian legacy editor and v2 to work with the new version.  Right now it says I have to manually install v1 to work with legacy editor so I can no longer auto update all my plugins.  Would love to see an option or to release themn as separate plugins even like a seperate plugin for legacy editor?

**Comment by vslinko** [comment]
@jasondavis thank you for your feedback!

I understand your problem, but I don't want to do that because of several reasons:
- I don't want to support Legacy Editor because I don't have time to properly support a modern editor
- any public release will be considered relevant and supported, and people will create new issues
- I just found a workaround

The workaround:
- install v1 of the plugin
- rename the folder `.obsidian/plugins/obsidian-outliner` to `.obsidian/plugins/obsidian-outliner-legacy`
- rename the plugin in `.obsidian/plugins/obsidian-outliner-legacy/manifest.json`

**Comment by Lulullia** [comment]
That's exactly what I did (even before searching for a solution online), but somehow once you modify the `manifest.json`, Obsidian no longer wants to show the plugin in the list.
Manually installing v1 works, but as soon as I try to rename the plugin in `manifest.json` in order to stop updates, it doesn't show in the list anymore.

Maybe Obsidian blocks modified files...?

I think you could fix the issue by updating the latest v1 release, with the already-renamed manifest?

**Comment by vslinko** [comment]
I created [a repository with the renamed plugin](https://github.com/vslinko/obsidian-outliner-legacy). You can easily install it with [BRAT](https://github.com/TfTHacker/obsidian42-brat) by specifying URL to the repository `https://github.com/vslinko/obsidian-outliner-legacy`.

**Comment by Lulullia** [comment]
Thanks, it works perfectly!
