### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by vslinko** [vslinko/obsidian-outliner#27]
See https://github.com/liamcain/obsidian-calendar-plugin for inspiration

- [x] More useful information
- [ ] Correct English
- [x] Some badges?
- [x] Commands documentation
- [ ] --Contribution guide--

**Comment by ShreyasKallingal** [comment]
I would love to help out with this! Do you have any instructions for contributing?

**Comment by vslinko** [comment]
@ShreyasKallingal Thank you for your intention! I don’t have any instructions yet. You can create pull request with all changes you want to make to readme.

**Comment by vslinko** [comment]
I just released 1.1.0-beta5 https://github.com/vslinko/obsidian-outliner/releases/tag/1.1.0-beta5

It could be the latest beta before public release.
I'm looking for beta testers for this release.
Please install 1.1.0-beta5 and report issues.

**Comment by SlRvb** [comment]
A suggestion is to put the description right under the headings instead of after the lists, it's a little confusing to have to look farther down to understand what the heading means.


**For example,** the parts under these headings I would write like this:
---


### Improve the style of your lists
If you liked the styles from the demo above, you can enable them in the plugin settings tab.

> **Disclaimer:** Styles are only compatible with built-in Obsidian themes and may not be compatible with other themes. Styles only work well with spaces or four-space tabs.

Settings:
- `Improve the style of your lists` (default `false`)



### Move lists back and forth
Move lists with children wherever you want without breaking the structure.

Commands:
- `Move list and sublists up` (default hotkey `Mod-Shift-ArrowUp`)
- `Move list and sublists down` (default hotkey `Mod-Shift-ArrowDown`)
- `Indent the list and sublists` (default hotkey `Tab`)
- `Outdent the list and sublists` (default hotkey `Shift-Tab`)

**Comment by SlRvb** [comment]
I also think it might be easier to read the commands if you used a markdown table.

For example:

Command | Default Hotkey
---|:---:|
Move list and sublists up |  `Mod-Shift-ArrowUp`
Move list and sublists down | `Mod-Shift-ArrowDown`
Indent the list and sublists | `Tab`
Outdent the list and sublists | `Shift-Tab`

**Comment by vslinko** [comment]
@SlRvb Made as you suggested https://github.com/vslinko/obsidian-outliner/tree/obsidian-commands

**Comment by vslinko** [comment]
@SlRvb It looks better! Thank you!
