### ISSUE TITLE
[BUG] Hover Editor Incompatibility

### ISSUE THREAD

**Issue by Servinjesus1** [vslinko/obsidian-outliner#507]
# Hover Editor Incompatibility

Opening notes in Hover Editor, regardless of if they have lists or not, throws an 'editor' like error. My issue is compound so I am exploring further but I've reproduced it in a sandbox vault.

**To Reproduce**

1. Enable [Hover Editor](https://github.com/nothingislost/obsidian-hover-editor) and Outliner
2. Hover to open an editor with console open
3. Note any 'undefined ( reading 'editor')' errors

**Environment:**
 - OS: MacOS
 - Obsidian Version: 1.5.3
 - Plugin Version: 4.8.0
 - Hover Version: 0.11.17

**Comment by pjeby** [comment]
Here is the error:

app.js:1 TypeError: Cannot read properties of undefined (reading 'editor')
    at t.get (app.js:1:2091356)
    at getEditorFromState (plugin:obsidian-outliner:88:13)
    at VerticalLinesPluginValue.waitForEditor (plugin:obsidian-outliner:2552:28)
    at new VerticalLinesPluginValue (plugin:obsidian-outliner:2602:14)
    at e.eval [as create] (plugin:obsidian-outliner:2795:82)
    at e.update (app.js:1:367539)
    at e.setState (app.js:1:468006)
    at t.clear (app.js:1:1378062)
    at t.clear (app.js:1:2086260)
    at t [as constructor] (app.js:1:1374961)

The issue is that this line:

```ts
const { editor } = state.field(obsidian.editorInfoField);
```

should be:

```ts
const editor = state.field(obsidian.editorInfoField)?.editor;
```

This appears to be a change to how Obsidian 1.5 initializes the editor, and it actually has nothing to do with Hover Editor -- the error happens on every new tab open.  Fortunately it only seems to affect vertical line generation.

**Comment by pjeby** [comment]
Whoops...  my proposed fix isn't quite correct; what actually works for me locally (patching main.js) is:

```ts
const { editor } = state.field(obsidian.editorInfoField).editMode?.editor;
```

I've also filed an [Obsidian API bug report](https://github.com/obsidianmd/obsidian-api/issues/156) for the underlying issue, which was introduced in Obsidian 1.5.0 a few months ago.  I think it's likely the cause of #501 here as well.

**Comment by Servinjesus1** [comment]
Thanks!

Since it's in progress where it's bugged, I'll consider it here closed. Appreciate your help identifying it!

**Comment by pjeby** [comment]
It looks like version 1.5.9 will have the fix, which is going to insider status shortly.

**Comment by aagha** [comment]
Here's the current state, using this code:

![image](https://github.com/vslinko/obsidian-outliner/assets/5522103/3308862c-54f2-46eb-8198-094bbffc73fe)

![image](https://github.com/vslinko/obsidian-outliner/assets/5522103/d9f190d8-be59-4d90-a8a8-ec70ec4f5e72)

If I add the #501 suggestion, the code changes:

![image](https://github.com/vslinko/obsidian-outliner/assets/5522103/8f48cc42-1bc0-487e-a6b9-3863c839062e)

The lines completely disappear:

![image](https://github.com/vslinko/obsidian-outliner/assets/5522103/e94572c4-443f-4647-bc7e-259b331de573)

**Comment by pjeby** [comment]
Ok, so it seems the other issue is related, since it does have an effect.  But clearly there's more to it than just that, and I don't know how to proceed further.  I will note, though, that Obsidian itself has an option to display indentation guides now (in the "Editor > Display" settings), and if you turn that on and turn Outliner's "Draw vertical indentation lines" off, you might end up with something workable.
