### ISSUE TITLE
[Feature request] Change the command + 'A' to highlight behavior

### ISSUE THREAD

**Issue by ShreyasKallingal** [vslinko/obsidian-outliner#8]
This plugin is amazing so far!

One feature that would be nice is changing how command + 'A' works. Currently, all the text in the entire file is highlighted at once. In most other outliner apps, command + 'A' will first highlight the current block, then highlight the parent block progressively until it reaches the root of the tree structure. I'm not sure if this would be possible, but it would be much appreciated :)

**Comment by vslinko** [comment]
@ShreyasKallingal good idea! I think I can do that.

**Comment by vslinko** [comment]
@ShreyasKallingal Added CMD+A suport in https://github.com/vslinko/obsidian-outliner/releases/tag/1.0.4

RN it works only with current line and whole tree because it's easy to implement.
You can follow separate issue to be notified about highlighting of parent block https://github.com/vslinko/obsidian-outliner/issues/9

**Comment by ShreyasKallingal** [comment]
Wow, that was fast. Thank you very much!
